package app.src.test.java;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import app.src.main.java.HelloWorld;

class AppTest {
    @Test void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
